### ISSUE TITLE
GOZNYM MALWARE

### ISSUE THREAD

**Issue by to4kawa** [gasgas4/APT_CyberCriminal_Campagin#10]
APRIL 14, 2016
Meet GozNym: The Banking Malware Offspring of Gozi ISFB and Nymaim
https://securityintelligence.com/meet-goznym-the-banking-malware-offspring-of-gozi-isfb-and-nymaim/

May 2,  2016
https://blog.team-cymru.org/2016/05/goznym-malware/

May 23, 2016
https://kc.mcafee.com/resources/sites/MCAFEE/content/live/PRODUCT_DOCUMENTATION/26000/PD26519/en_US/McAfee%20Labs%20Threat%20Advisory%20-%20Goznym_Banking_Trojan.pdf

**Comment by gasgas4** [comment]
thanks..

you can find the data here now https://github.com/gasgas4/APT_CyberCriminal_Campagin/tree/master/2016/2016.05.02.GOZNYM_MALWARE
