### ISSUE TITLE
The new RAA Ransomware is created entirely using Javascript

### ISSUE THREAD

**Issue by to4kawa** [gasgas4/APT_CyberCriminal_Campagin#11]
June 13, 2016
http://www.bleepingcomputer.com/news/security/the-new-raa-ransomware-is-created-entirely-using-javascript/

**Comment by gasgas4** [comment]
this is a technique but not in any APT/cybercriminal group right now.  so I will keep it but not add to repository

**Comment by to4kawa** [comment]
Do you know what repository is suitable for technical articles?

**Comment by to4kawa** [comment]
I see. What are you doing to the WEB to PDF?

**Comment by gasgas4** [comment]
I use python's module to it.

please see my program in attachments,

running
[image: Inline image 1]
