### ISSUE TITLE
Threat Update: Nigerian Cybercriminals Target High-Impact Industries in India via Pony

### ISSUE THREAD

**Issue by to4kawa** [gasgas4/APT_CyberCriminal_Campagin#12]
June 28, 2016
https://blog.cylance.com/threat-update-nigerian-cybercriminals-target-high-impact-indian-industries-via-pony

**Comment by gasgas4** [comment]
Dear to4kawa, 
  
   This article is collected and can be found in https://github.com/gasgas4/APT_CyberCriminal_Campagin/tree/master/2016/2016.06.26.Nigerian_Cybercriminals_Target_High_Impact_Industries_in_India

thanks
