### ISSUE TITLE
Massive Admedia/Adverting iFrame Infection

### ISSUE THREAD

**Issue by to4kawa** [gasgas4/APT_CyberCriminal_Campagin#3]
Feb 1
https://blog.sucuri.net/2016/02/massive-admedia-iframe-javascript-infection.html

**Comment by gasgas4** [comment]
Thanks to4kawa,  I put in https://github.com/gasgas4/APT_CyberCriminal_Campagin/tree/master/2016/2016.02.01.Massive_Admedia_Adverting_iFrame_Infection now.
