### ISSUE TITLE
 Banking Malware: Big in Japan

### ISSUE THREAD

**Issue by to4kawa** [gasgas4/APT_CyberCriminal_Campagin#4]
Feb 1
https://securityintelligence.com/organized-cybercrime-big-in-japan-urlzone-now-on-the-scene/

**Comment by gasgas4** [comment]
Thanks to4kawa

The data is including in https://github.com/gasgas4/APT_CyberCriminal_Campagin/tree/master/2016/2016.02.01.URLzone_Team now
