### ISSUE TITLE
Malicious Office files dropping Kasidet and Dridex

### ISSUE THREAD

**Issue by to4kawa** [gasgas4/APT_CyberCriminal_Campagin#5]
Jan 29
http://research.zscaler.com/2016/01/malicious-office-files-dropping-kasidet.html

**Comment by gasgas4** [comment]
Thanks to4kawa,   including in the https://github.com/gasgas4/APT_CyberCriminal_Campagin/tree/master/2016/2016.01.29.Malicious_Office_files_dropping_Kasidet_and_Dridex now
