### ISSUE TITLE
Shedding Light on BlackEnergy With Open Source Intelligence

### ISSUE THREAD

**Issue by to4kawa** [gasgas4/APT_CyberCriminal_Campagin#6]
March 3, 2016
https://www.recordedfuture.com/blackenergy-malware-analysis/

**Comment by gasgas4** [comment]
Thank the data.  Now can find in https://github.com/gasgas4/APT_CyberCriminal_Campagin/tree/master/2016/2016.03.03.Shedding_Light_BlackEnergy
